import os

from aoc_tools import get_data

debug_part1 = True
debug_part2 = False


def find_parts(schematic):
    parts = {}
    for i in range(len(schematic)):
        row = schematic[i]
        for j in range(len(row)):
            ch = row[j]
            if ch.isdigit():
                continue
            if ch == ".":
                continue

            parts[(i, j)] = ch
    return parts


def has_adjacent_part(dn, parts):
    j1 = dn[2] - 1
    j2 = dn[2] + 1 + dn[3]

    rn = dn[1]
    for i in [rn - 1, rn, rn + 1]:
        for j in range(j1, j2):
            if (i, j) in parts:
                return True

    return False


def part1(data):
    result = 0

    input_lines = data.splitlines()
    schematic = [x for x in input_lines]
    if debug_part1:
        for line in schematic:
            print(line)
        print()

    parts = find_parts(schematic)

    numbers_detected = []

    buffer = ""
    for i in range(len(schematic)):
        row = schematic[i]
        for j in range(len(row)):
            char = row[j]
            if char.isdigit():
                buffer += char
                continue
            if len(buffer) > 0:
                detected_number = (int(buffer), i, j - len(buffer), len(buffer))
                numbers_detected.append(detected_number)
                buffer = ""
        if len(buffer) > 0:
            detected_number = (int(buffer), i, len(row) - 1 - len(buffer), len(buffer))
            numbers_detected.append(detected_number)
            buffer = ""

    print(numbers_detected)
    print(parts)

    for dn in numbers_detected:
        if has_adjacent_part(dn, parts):
            # if debug_part1:
            #     print(dn, "is part number")
            result += int(dn[0])
        else:
            if debug_part1:
                print(dn, "is not part number")
    return result


def part2(data):
    pass


def do_tests():
    testdata1 = """467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598.."""
    testdata2 = """++++++++++++
++++++++++++
++++++++++++
++*.....*+++
++*.123.*+++
++*.....*+++
++**+++**+++
++++...+++++
++++.1.+++++
++++...+++++
++++++++++++"""
    testdata3 = """..........
..........
..........
..r.......
...100....
..........
..........
..........
..........
..........
...r......
...200....
..........
..........
..........
..........
..........
....r.....
...300....
..........
..........
..........
..........
..........
.....r....
...400....
..........
..........
..........
..........
..........
......r...
...500....
..........
..........
..........
..........
..........
..........
...600r...
..........
..........
..........
..........
..........
..........
...700....
......r...
..........
..........
..........
..........
..........
...800....
.....r....
..........
..........
..........
..........
..........
...900....
....r.....
..........
..........
..........
..........
..........
...110....
...r......
..........
..........
..........
..........
..........
...111....
..r.......
..........
..........
..........
..........
..........
..r112....
..........
..........
..........
"""
    print(part1(testdata1))
    print(part2(testdata1))


if __name__ == "__main__":
    input_data = get_data(os.path.basename(__file__))

    do_tests()

    print(part1(input_data))
    print(part2(input_data))
