import unittest

import day07

test_data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


class AoCTest(unittest.TestCase):

    def test_part1(self):
        self.assertEqual(21, day07.part1(test_data))

    def test_part2(self):
        self.assertEqual(40, day07.part2(test_data))


if __name__ == '__main__':
    unittest.main()